name: Copy DBA Content to Deploy Branch

on:
  workflow_dispatch:

jobs:
  copy-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy
          path: deploy

      - name: Copy DBA files
        run: |
          mkdir -p deploy/content/dba
          cp main/mariadb-dba* deploy/content/dba/
          cd deploy
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add content/dba/
          git commit -m "Copy DBA content from main branch" || echo "No changes to commit"
          git push origin deploy 